<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <title>Добро пожаловать</title>
    <link href="https://fonts.googleapis.com/css?family=Teko" rel="stylesheet">
    <link rel="stylesheet" href="../view/css/stylesheet.css">
</head>
<body>
<div class="wrapper">
    <div class="inner">
        <header class="header">
            <div class="header-img">
                <img src="../view/css/image.png" alt="img">
            </div>
            <span class="title"><?php echo $welcome; ?></span>

            <ul class="header-list">
                <li class="header-list-item"><a href="#" title="Ссылка на запись" rel="bookmark">Главная</a></li>
                <li class="header-list-item"><a href="index.phtml">Добавление пользователей</a></li>
                <li class="header-list-item"><a href="#">Новая запись</a></li>
                <li class="header-list-item"><a href="#">Пользователи</a></li>
                <li class="header-list-item"><a href="#">Контакты</a></li>
                <li class="header-list-item"><a href="#">О нас</a></li>
            </ul>
        </header>
        <footer>
            <p>&copy; My task</p>
        </footer>
    </div>
</div>
</body>
</html>